name: neus-sl-blur-david-david_opt0_n3_f128-Supp
tag: a1-1_a2-1_Back-False_avg-1_normal-True
seed: 42
dataset:
  category: captured-geoalbamb
  opengl: false
  noise: false
  denoise: false
  name: sl
  scene_object: david
  capture_id: david
  num_patterns: 3
  family_patterns: opt0
  freq_patterns: 128
  scene: david_opt0_n3_f128
  gt_scene: david_opt0_n30_f32
  root_dir: ../data/captured_data/david/david_opt0_n3_f128
  gt_dir: ../data/captured_data/david/david_opt0_n30_f32
  avg_itr: 1
  img_downscale: 1
  near_plane: 2.0
  far_plane: 6.0
  spheric_poses: false
  use_pixel_centers: true
  train_split: train
  val_split: val
  test_split: test
  camera_angle_x: 0.6911112070083618
model:
  opengl: false
  name: neus-geometry-albedo-ambient-wz-camproblur
  radius: 1.5
  back_rendering: false
  use_normal: true
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: 20000
  learned_background: false
  background_color: black
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: 1.5
    feature_dim: 1
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.0
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
      sphere_init: false
      sphere_init_radius: 0.5
      weight_norm: true
  albedo:
    name: 2d-implicit-albedo
    n_input_dim: 2
    n_output_dim: 1
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 15
      base_resolution: 16
      per_level_scale: 1.447269237440378
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: sigmoid
      n_neurons: 64
      n_hidden_layers: 2
  ambient:
    name: 2d-implicit-ambient
    n_input_dim: 2
    n_output_dim: 1
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 15
      base_resolution: 16
      per_level_scale: 1.447269237440378
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: sigmoid
      n_neurons: 64
      n_hidden_layers: 2
  blur:
    projector_blur_flag: true
    name: 2d-projector-kernel-wz-center
    in_channel: 3
    kernel_size: 11
    blurstart: 1000
    normalize: 0
    blurprojectorside: 1
system:
  name: neus-sl-system-geometry-albedo-ambient-wz-camproblur
  loss:
    lambda_rgb_mse: 10.0
    lambda_rgb_l1: 1
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_sparsity: 0.01
    sparsity_scale: 1.0
    alpha1: 1
    alpha2: 1
  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
    params:
      geometry:
        lr: 0.0008
      variance:
        lr: 0.0008
      albedo:
        lr: 0.008
      ambient:
        lr: 0.008
      blur:
        lr: 0.008
  warmup_steps: 500
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
    - 500
    schedulers:
    - name: LinearLR
      args:
        start_factor: 0.01
        end_factor: 1.0
        total_iters: 500
    - name: ExponentialLR
      args:
        gamma: 0.9997576519928139
checkpoint:
  save_top_k: -1
  every_n_train_steps: 10000
trainer:
  max_steps: 10000
  log_every_n_steps: 50
  num_sanity_val_steps: -1
  val_check_interval: 2000
  limit_train_batches: 1.0
  limit_val_batches: 2.0
  enable_progress_bar: true
  precision: 32
cmd_args:
  config: configs/neus-sl-geoalbamb-capture-blur.yaml
  gpu: '0'
  resume: null
  resume_weights_only: false
  train: 'True'
  validate: 'False'
  test: 'False'
  predict: 'False'
  exp_dir: ./train_david
  runs_dir: ./runs
  verbose: false
trial_name: a1-1_a2-1_Back-False_avg-1_normal-True@20241127-173920
exp_dir: ./train_david/neus-sl-blur-david-david_opt0_n3_f128-Supp
save_dir: ./train_david/neus-sl-blur-david-david_opt0_n3_f128-Supp/a1-1_a2-1_Back-False_avg-1_normal-True@20241127-173920/save
ckpt_dir: ./train_david/neus-sl-blur-david-david_opt0_n3_f128-Supp/a1-1_a2-1_Back-False_avg-1_normal-True@20241127-173920/ckpt
code_dir: ./train_david/neus-sl-blur-david-david_opt0_n3_f128-Supp/a1-1_a2-1_Back-False_avg-1_normal-True@20241127-173920/code
config_dir: ./train_david/neus-sl-blur-david-david_opt0_n3_f128-Supp/a1-1_a2-1_Back-False_avg-1_normal-True@20241127-173920/config
